<?php

require_once "Database.php";

$vehicleSQL = $db->conn->prepare("INSERT INTO vehicles (
        id,
        title,
        stat,
        content,
        created,
        last_modified,
        edit_lock,
        edit_last,
        tracker,
        vehicletype,
        adjust,
        fleet,
        last_maintenance,
        last_report,
        deploy,
        b2blocation,
        b2blocation_coordinates,
        sleutelcode,
        station_based,
        project,
        special_project_desc,
        lastpump,
        station_coords,
        yeply
    ) VALUES (
        :_id,
        :_title,
        :_stat,
        :_content,
        :_created,
        :_last_modified,
        :_edit_lock,
        :_edit_last,
        :_tracker,
        :_vehicletype,
        :_adjust,
        :_fleet,
        :_last_maintenance,
        :_last_report,
        :_deploy,
        :_b2blocation,
        :_b2blocation_coordinates,
        :_sleutelcode,
        :_station_based,
        :_project,
        :_special_project_desc,
        :_lastpump,
        :_station_coords,
        :_yeply
    )");

$gpsSQL = $db->conn->prepare("INSERT INTO gps (
        id,
        title,
        attribute_b2b,
        attribute_firmware,
        attribute_guarded,
        attribute_alarm,
        attribute_lastAlarm,
        groupId,
        uniqueId,
        stat,
        lastUpdate,
        positionId,
        geofenceIds,
        phone,
        model,
        contact,
        category,
        isDisabled,
        positions_id,
        positions_armed,
        positions_charge,
        positions_ignition,
        positions_stat,
        positions_distance,
        positions_totalDistance,
        positions_motion,
        positions_batteryLevel,
        positions_hours,
        deviceId,
        thisType,
        protocol,
        serverTime,
        deviceTime,
        fixTime,
        outdated,
        valid,
        latitude,
        longitude,
        altitude,
        speed,
        course,
        thisAddress,
        accuracy,
        network
    ) VALUES (
        :_id,
        :_title,
        :_attribute_b2b,
        :_attribute_firmware,
        :_attribute_guarded,
        :_attribute_alarm,
        :_attribute_lastAlarm,
        :_groupId,
        :_uniqueId,
        :_stat,
        :_lastUpdate,
        :_positionId,
        :_geofenceIds,
        :_phone,
        :_model,
        :_contact,
        :_category,
        :_isDisabled,
        :_positions_id,
        :_positions_armed,
        :_positions_charge,
        :_positions_ignition,
        :_positions_stat,
        :_positions_distance,
        :_positions_totalDistance,
        :_positions_motion,
        :_positions_batteryLevel,
        :_positions_hours,
        :_deviceId,
        :_thisType,
        :_protocol,
        :_serverTime,
        :_deviceTime,
        :_fixTime,
        :_outdated,
        :_valid,
        :_latitude,
        :_longitude,
        :_altitude,
        :_speed,
        :_course,
        :_thisAddress,
        :_accuracy,
        :_network
    )");












?>